name: Clang format check

on:
  workflow_dispatch: null
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: 'SRC'
        clangFormatVersion: 14
    - name: Display how to fix
      if: failure()
      run: |
        echo "::notice::Run the following commands to autofix the linter error and commit the changes:"
        echo "::notice::docker build -t clang-format-lint github.com/DoozyX/clang-format-lint-action"
        echo "::notice::docker run -it --rm --workdir /src -v \$(pwd):/src clang-format-lint --clang-format-executable /clang-format/clang-format15 -r -i true SRC"
        /bin/false
